### ISSUE TITLE
SetSession/Session does not make sense when using TLS

### ISSUE THREAD

**Issue by troian** [lesismal/nbio#140]
As per doc both `SetSession` and `Session` are aimed to be used by end user to set own session context. And approach works fine up until TLS required.

`WrapOpen` [sets tls context](https://github.com/lesismal/nbio/blob/f1f2c164d5cec5891d24b7a98d38b8b41443ff8f/extension/tls/tls.go#L26) as session which breaks flow if user later wanna set own session object.

Would it make sense to actually let tls to implement Session methods and wrap Conn into tlsConn rather than doing it opposite side as end client should not know about any underlying transports rather than just having `net.Conn` interface.

**Comment by lesismal** [comment]
Firstlly, `nbio/extension/tls` is just an example to show how can we use non-blocking tls on nbio.Conn, and users can easily copy and rewrite the tls-extension for their own service and customize the session value type(maybe a struct with more fields) like here:
here https://github.com/lesismal/nbio/blob/master/extension/tls/tls.go#L35

Secondly, if we implement an HTTP service using `nbio/nbhttp` with tls, we usually do not need to operate nbio.Conn because the HTTP is non-state between multi requests.

Thirdly, if we are serving Websocket using `nbio/nbhttp/websocket`, the `websocket.Conn` already have the `Session/SetSession` methods:
https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/conn.go#L187

> Would it make sense to actually let tls to implement Session methods and wrap Conn into

And of course, if you really need the `tls.Conn.Session/SetSession` methods, we'll be glad to do it.

**Comment by troian** [comment]
So, idea behind what i’m talking is next. Regardless to what kind of transport is used the client shouldn’t worry about it. What it expects is interface that is same across all implementations.

So yeah, TLS kinda needs SetSession/Session.

**Comment by lesismal** [comment]
ok, done:
https://github.com/lesismal/llib/releases/tag/v1.1.4
https://github.com/lesismal/nbio/releases/tag/v1.2.8

please try it :smile:

**Comment by troian** [comment]
sorry, had a busy schedule. I'll give it a try in a next few days
