### ISSUE TITLE
MQTT support

### ISSUE THREAD

**Issue by cexll** [lesismal/nbio#218]
Any plans to add MQTT?

mqtt does not yet have a netpoll related library

**Comment by lesismal** [comment]
There isn't a plan for MQTT yet, but maybe in the future. It's better if other developers who are familiar with MQTT implement it based on nbio.

**Comment by lesismal** [comment]
I hear that there're lots of connections for an IoT service.
I am not familia with IoT but wonder how many connections connect to each of your service nodes.

**Comment by cexll** [comment]
Many nio libraries do not support tls

**Comment by cexll** [comment]
github.com/wind-c/comqtt

**Comment by cexll** [comment]
Choose to use nbio today as the tcp communication for the Internet of Things

**Comment by lesismal** [comment]
I'll do some investments to learn about MQTT.

**Comment by cexll** [comment]
Very looking forward to the 
new Internet of Things project using nbio is very good

**Comment by lesismal** [comment]
I already did some research about `MQTT`. Unlike an `http/websocket` server for which we still need to write a lot of logic code, for an `MQTT Broker`, we don't need to develop new features for a `Broker` because the features are defined by the protocol itself and contained by a `Broker` no matter implemented by which language.
Compared with the current implementations of a `Broker` by other languages, the implementation of golang will not perform better than that implemented by `c/cpp/rust`.
So, I think we don't need to implement a golang edition for `Broker`.

For the client side, there wouldn't be a huge num of online connections, so the num of goroutines and the mem cost would not be a problem even if the client is based on std.

Therefor, I think we don't really need an implementation based on `nbio`.

**Comment by lesismal** [comment]
I also planned to support the `audio/video` protocol, but give up because of the same reason that we don't need to extend the protocol, and most important that golang doesn't perform better than `c/cpp/rust` in such scenarios.

Maybe we should learn `rust` someday :joy:

**Comment by cexll** [comment]
yes it's good now

**Comment by cexll** [comment]
> I also planned to support the `audio/video` protocol, but give up because of the same reason that we don't need to extend the protocol, and most important that golang doesn't perform better than `c/cpp/rust` in such scenarios.
> 
> Maybe we should learn `rust` someday 😂

en, rust is more suitable for some scenarios

**Comment by cexll** [comment]
close
