### ISSUE TITLE
Question: performance gain for one-way communication?

### ISSUE THREAD

**Issue by ivanjaros** [lesismal/nbio#244]
I will be writing a chat server where writes will go to server A and reads will come from server B. This B server will be a websocket server that will distribute messages to connected users. Since these websocket connections will be constantly open and mostly one way(client will just send subscription to specific room but other than that is just listens for messages) I wonder if there is any actual performance I could gain from using this library? As far as I understand, standard library's overhead comes from goroutines per each connection and context switching for each connection and these goroutines. So if I will not have a request/response setup where connections are constantly opened and closed, which cause new goroutines to be created and killed and memory consumed and freed, but instead are constantly open, can this library provide any actual performance in the amount of clients the server can handle by using less memory/cpu? Because it looks to me like this is the exact use case where there cannot be any performance gain achieved.

**Comment by lesismal** [comment]
In a scenario with the normal num of online connections, `nbio`(`IOModNonBlocking`) doesn't perform better than std. In version 1.3.5+, `nbio` supports `IOModMixed` to gain both performance and balance between performance and `cpu/mem` cost, details for `IOModMixed`: https://github.com/lesismal/nbio/releases/tag/v1.3.5

I can't give you an exact result for your real business, that depends on your online num, your implementation of your logic, and maybe some details of how you use `nbio`. There's a simple way to get the result: write the test code and run it.

Since there's `Websocket`, I think your business should use both `TCP` and `Websocket` with `Keepalive` style. The disconnected logic should be triggered by users and is not very frequently happening on each connection, unlike HTTP1.0 which just disconnects after a request-response so that the `TCP Handshake RTT` wastes too much time.
If your online num is not huge, it should not be a problem even if your service is based on std's solution that serves each connection with at least 1 goroutine, cause the goroutine's create and killed is also well optimized in the latest version of golang, the goroutine may be not released at once after the function is returned, and then may be reused. I did some benchmark and it seems goroutine pools like `panjf/ants`, bytedance's pool, or my pool implementation for nbio, they don't perform better than std in the benchmark with a limited size of concurrent goroutines.

In `nbio`, if there's no request, the connection won't hold a goroutine. 
The default goroutine pool doesn't hold many goroutines at the same time, the implementation is simple, you can take a look at it and run the benchmark, also you can add other goroutine pool libs to compare the performance:
https://github.com/lesismal/nbio/blob/master/taskpool/mixedpool.go

About the amount of clients `nbio` can serve, I'd say that, with the same hardware, it can serve much more than std, it also depends on what your service is really like:
1. Is it handles lots of messages with big size body? 
2. Is it a high-speed service with high qps/tps? 
3. Some other details...

We can't just guess and then get the result of the performance and cpu/mem cost without the details of your real service logic. 
But fortunately, I make `nbio` very flexible, it supports many ways to custom and optimize your service, such as goroutine pool, buffer pool, timer, connection IO deadline, read/write buffer size, read limit for parsing, and so on.

If the `qps/tps` you want are not beyond the ability of `golang` on the hardware, we can optimize or gain the balance as much as possible based on `nbio`.
