### ISSUE TITLE
Benchmark against FastHTTP

### ISSUE THREAD

**Issue by om26er** [lesismal/nbio#254]
I think it would be interesting to see how NBIO stands compared to FastHTTP https://github.com/valyala/fasthttp in terms of memory usage and performance. Maybe we should do an effort to test that out ?

**Comment by lesismal** [comment]
I did some tests last year.

nbio performs a slower than FastHTTP if not a huge num of connections else reduces lots of mem usage and perform better but different business and hardware, different threshold.

It seems we can't gain a better performance in poller framework because we need to use more heap obj/buffers, more heap escapes, and much more complex parsing logic and half-packet cache.

For the Blocking mod or the Blocking connections in Mixed mod, we may be able to make another implementation to achieve nearby/better performance than FastHTTP, but the current version of nbhttp aims to keep compatible with net/http, so we can't do the improvements as FastHTTP did, such as raw buffer used as HTTP header/body's key-value and pools of variables and buffers.

**Comment by om26er** [comment]
Closing. I am going to run some numbers against FastHTTP for my websocket server case and will share the results when I have something

**Comment by lesismal** [comment]
If for websocket, nbio may run faster when using Blocking mod.
It seems this implementation based on fasthttp performs worse: `github.com/dgrr/fastws`

**Comment by om26er** [comment]
I my testing from the past, the websocket connection establishment is quite a slow process. I was essentially able to connect 1000 new clients per second. This is on a localhost. Image a server with 100k connects gets restarted, it would take quite a few seconds for all the clients to reconnect

**Comment by lesismal** [comment]
It seems you need fast Accept, nbio.Engine support to extend for multi listeners on same port by using `reuseport`, but nbhttp.Engine doesn't support the extention, I'll think about that feature.

For the current versioin, if need fast Accept, maybe can use `reuseport` on multi engine like this:
```golang
package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"runtime"
	"sync"
	"time"

	"github.com/lesismal/nbio/nbhttp"
	"github.com/lesismal/nbio/nbhttp/websocket"
	"github.com/libp2p/go-reuseport"
)

func onWebsocket(w http.ResponseWriter, r *http.Request) {
	upgrader := websocket.NewUpgrader()
	upgrader.OnMessage(func(c *websocket.Conn, messageType websocket.MessageType, data []byte) {
		c.WriteMessage(messageType, data)
	})
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		w.WriteHeader(http.StatusForbidden)
		return
	}
	conn.SetReadDeadline(time.Now().Add(time.Second * 30))
}

func main() {
	mux := &http.ServeMux{}
	mux.HandleFunc("/ws", onWebsocket)

	// multi engine, multi listener
	listnerNum := runtime.NumCPU()
	engines := make([]*nbhttp.Engine, listnerNum)
	for i := 0; i < listnerNum; i++ {
		engine := nbhttp.NewEngine(nbhttp.Config{
			Network: "tcp",
			Addrs:   []string{"localhost:8888"},
			Handler: mux,
			NPoller: runtime.NumCPU() / listnerNum * 2, // adjust this num by business
			Listen:  reuseport.Listen,                  // multi listener on the same port
		})

		err := engine.Start()
		if err != nil {
			for j := 0; j < i; j++ {
				engines[j].Stop()
			}
			log.Fatalf("nbhttp.Engine Start failed: %v\n", err)
		}
		engines[i] = engine
	}

	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)
	<-interrupt

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*5)
	defer cancel()
	wg := sync.WaitGroup{}
	for _, e := range engines {
		wg.Add(1)
		engine := e
		go func() {
			defer wg.Done()
			engine.Shutdown(ctx)
		}()
	}
	wg.Wait()
}
```
