### ISSUE TITLE
If the client is closed too quickly, the server will not receive messages

### ISSUE THREAD

**Issue by ydedev** [lesismal/nbio#350]
```
	addr = "127.0.0.1:1833"

		conn, err := net.Dial("tcp", addr)
		if err != nil {
			return err
		}
               defer conn.Close()
	      conn.Write([]byte("hi"))
```
Use this to solve
	      
```
	time.AfterFunc(1*time.Second, func() {
			defer conn.Close()
		})
```

**Comment by lesismal** [comment]
Thanks for the feedback, but sorry to say that I don't get the point of what you want to ask...
Are you telling the solution for https://github.com/lesismal/nbio/issues/347?

**Comment by ydedev** [comment]
This is the problem, thank you for solving it

**Comment by lesismal** [comment]
Do you need me to solve it?

**Comment by ydedev** [comment]
Maybe the websocket is fine, but the test tcp still cannot receive it.I hope you can solve it, thank you for your efforts

**Comment by lesismal** [comment]
I'm a little confused because you both asked the question and wrote the answer.
So what do you want me to do?

Back to this problem, you can try dev branch, I've just add delay for async write today:
```sh
go get -u github.com/lesismal/nbio@dev
```

**Comment by lesismal** [comment]
Ah, tcp client.
Please provide the full example including server and client.

**Comment by lesismal** [comment]
It's because in the event loop, nbio gets the EOF and data in the same event loop.
Usually, if a connection has been closed by another side, there's no need to continue reading the data.
So nbio handles the events in such order:
1. err events
2. write event 
3. read events 

When nbio gets err events, just close and stop handling the other events, so we lose the data in your example.

I just make a commit to change the events handling order to:
1. write event 
2. read events 
3. err events

Please try this commit:
```sh
go get -u github.com/lesismal/nbio@1c01c70
```

**Comment by lesismal** [comment]
> It's working normally now, thank you

Thank you for your feedback!
