### ISSUE TITLE
Race condition in connection upgrade

### ISSUE THREAD

**Issue by iclita** [lesismal/nbio#449]
Hi,

While performing my service's performance testing, I found a race condition in the `Connection Upgrade` flow.
<img width="892" alt="Screenshot 2024-10-11 at 09 22 27" src="https://github.com/user-attachments/assets/43e9f82d-6dd8-447d-b0cb-6dd43bb85ee8">
<img width="891" alt="Screenshot 2024-10-11 at 09 22 47" src="https://github.com/user-attachments/assets/a48a2f18-ea23-4930-a434-52372f8dbc8c">
<img width="609" alt="Screenshot 2024-10-11 at 09 23 02" src="https://github.com/user-attachments/assets/e454f400-9f53-493f-97e0-d1a15908c6a5">

Could you please have a look?

Thanks and have great weekend ahead!

**Comment by lesismal** [comment]
https://github.com/lesismal/nbio/issues/446#issuecomment-2377166050 , As we talked last time, I have added //go:norace for all funcs, please try:
```sh
go get -u github.com/lesismal/nbio@f4cca21b6c56d57d3eee322b9f1c0694bd5a382d
```

**Comment by iclita** [comment]
Thanks for the reply. 

Appreciate the quick feedback.

I missed the point, and I'm very sorry about that. Last time, I wasn't concerned since it happened when the connection was about to be closed. But this time, it happens right at the start, when the connection gets upgraded.

I don't think it's ok to ignore race conditions. I mean, it's ok that you created a `norace` tag but, in my humble opinion, the regular library should be race condition free, and the `norace` one should ignore race conditions, as it currently does.

I mean, there is no mention about spurious race conditions that could pop up randomly. At least, if you're ignoring race conditions, document your reasoning behind this decision. Ignoring race conditions, without solid reasons, is not ideal, if you ask me.


Again, this is just my opinion. It's not a critique, just an opinion. In the end, it's your library and you could whatever you want, in the end. It's your call, not mine.

**Comment by iclita** [comment]
And, yes, I know it's very tough to have high performance without race conditions in a situation like this. But, at least, you can document those race conditions so people are aware. Just my 2cents.

**Comment by lesismal** [comment]
> I mean, there is no mention about spurious race conditions that could pop up randomly. At least, if you're ignoring race conditions, document your reasoning behind this decision. Ignoring race conditions, without solid reasons, is not ideal, if you ask me.


There are too many race warnings, the most important, we cannot get all the warnings in one test. Most of the race warning detections depend on concurrent relations between different goroutines but we can't decide how the goroutines race with each other.
For example, in the same test code, we may get race warning A at this time, but we won't get A next time.
Since we can't get all of them, I can't provide a reason for all the race warnings.

But, for every usage that may produce race warnings, I try to write and review it carefully.

For the shutdown race warning in another issue, I think it's safe because we can read the length of map even when we are writing it concurrently, and it doesn't matter for the shutting down step because before zero online we'll try more times.

For this ReleaseWebsocketPayload config, it's a little complex historically:
engine.ReleaseWebsocketPayload exists in the earlier version, and many users use it;
I added upgrader.ReleaseWebsocketPayload in the later version to make it more suitable for websocket config.
Both of these two are false by default.
Most of the users use 1 of them.
If user want to custom different websocket conn, they can use different upgrader instead of using the same upgrade to Upgrade all websocket conns.
For the common usage, this race warning is two conn's Upgrade happened at the same time: 1 is setting while 2 is reading ReleaseWebsocketPayload. No matter what value the 2 goroutine/conn gets, the  ReleaseWebsocketPayload will be the same value as engine.ReleaseWebsocketPayload.
The best choice of the implementations is to give up the engine.ReleaseWebsocketPayload, but consider of compatibility with old versions, we can not. If you have a good idea, welcome to PR or just tell me how and I'd like to change it.

Your opinion and suggestion are very good. I also want to make it perfect but just difficult.

**Comment by lesismal** [comment]
For example, the slice that stores pollers and conns:
https://github.com/lesismal/nbio/blob/master/engine.go#L138
https://github.com/lesismal/nbio/blob/master/engine.go#L142

This is the most effective way to store the pollers and conns, no mutex operations, we can visit the item by index directly.
But in the whole program, many goroutines running concurrently and in any one or more of the goroutines, we may call a websocket.Conn.Close, that could lead to multi concurrent nbio.Conn.Close and remove the conns from engine.connsUnix, while also the poller may be handling io events and visit the engine.connsUnix concurrently too. All of these concurrent operations can lead to race warning but that depends not only how we write the test code but also how the goroutines running and being scheduled at the same time. 

So, there isn't a way to produce and cover all the possible race warnings produced by nbio.
I feel sorry about this but that's the truth and the reason why I use //go:norace rather than more mutex.
