### ISSUE TITLE
autobahn test failures on tls

### ISSUE THREAD

**Issue by acgreek** [lesismal/nbio#56]
Here is the latest test report. We are all good when not running through tls. A few tests in section section 9 fail  

[report-2021-07-03.tar.gz](https://github.com/lesismal/nbio/files/6758516/report-2021-07-03.tar.gz)

**Comment by acgreek** [comment]
You should update your top level readme to advertise the autobahn test success

**Comment by lesismal** [comment]
Please confirm that you run autobahn test with the latest nbio. I run it and get this report, seems every test success for non-sticky-proxy server.
but some large message failed for the sticky-proxy server.

[report-tls-sticky-failed.gz](https://github.com/lesismal/nbio/files/6758772/report-tls-sticky-failed.gz)

The sticky-proxy helps to find out parsing bugs but may cost lots of time for the large messages. 
Since the failures are out of time as shown below, and it is successful in the test with non-sticky-proxy server, we may not need a sticky-proxy for the large messages.
![image](https://user-images.githubusercontent.com/40462947/124362470-9e450e00-dc67-11eb-832d-1884dbef797a.png)

**Comment by lesismal** [comment]
> You should update your top level readme to advertise the autobahn test success

Good idea, thanks, updated it already, is it seems good? Or you can edit it to help!

**Comment by acgreek** [comment]
Yeah, the newer tests run are not run against the sticky proxy. Instead they are run against Examples/websocket/server_autobahn

**Comment by lesismal** [comment]
> Yeah, the newer tests run are not run against the sticky proxy. Instead they are run against Examples/websocket/server_autobahn

are you sure that is using github.com/lesismal/llib v1.0.4, and whether it fails if run agian?

I run the test again and have not reproduced the failures:
[report-2021-07-04.tar.gz](https://github.com/lesismal/nbio/files/6759380/report-2021-07-04.tar.gz)

**Comment by acgreek** [comment]
I'm running on a 3 year old macbook and the Makefile runs the nbio server in a docker container. It could be that the overhead of running docker on mac makes it just slow enough to fail.

**Comment by acgreek** [comment]
actually, just re-ran autobahn and all the test results are green. Thanks.

**Comment by acgreek** [comment]
Was reading the wrong report. Still could be mac book, though the wait time on some of these are pretty long. For example 9.1.5 is "Did not receive message within 100 seconds."

**Comment by lesismal** [comment]
> Was reading the wrong report. Still could be mac book, though the wait time on some of these are pretty long. For example 9.1.5 is "Did not receive message within 100 seconds."

Try with a larger `ReadBufferSize` , to see whether it goes better:

```golang
svrTLS := nbhttp.NewServerTLS(nbhttp.Config{
	Network:        "tcp",
	Addrs:          []string{"localhost:9999"},
	ReadBufferSize: 1024 * 1024,
}, mux, nil, tlsConfig)
```

**Comment by acgreek** [comment]
that worked. Thanks
